### ISSUE TITLE
I am getting "Invalid hook call" error. Anybody knows how to solve it?

### ISSUE THREAD

**Issue by YasinFatullayev** [Allandrow/React-TS-dataTable#1]
```javascript
react.development.js:1476 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476:1)
    at useState (react.development.js:1507:1)
    at useTable (useTable.js:9:1)
    at Datatable (Datatable.tsx:54:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
```

**Comment by Allandrow** [comment]
Hi ! Could you give me more information about the way you are trying to use the library ? This error is a bit generic and would mean that you are trying to use one of the custom hook exposed by the library in a way that isn't intended.

If you haven't already I'd recommend checking the documentation and more specifically the [demo on  stackblitz](https://stackblitz.com/edit/react-ts-4mkzz9?embed=1&file=modules/dataTable/DataTable.tsx) to see an example of working implementation.

Finally fair warning, this project was used as a learning project during a scholar cursus that ended some time ago, it isn't maintained and is unlikely to evolve, so I'd probably recommend to use a more reputable library depending of your needs.

**Comment by YasinFatullayev** [comment]
Hi Allan, I just copied and pasted the exact project you referenced. I did no customization. I thought it was because of the webpack version and downgraded my webpack. But still no luck. I tried some other data table libraries such as bootstrap they have versioning problems too

**Comment by Allandrow** [comment]
That's weird, I tried to reproduce this issue on a new project and had no error whatsoever, could you share some code where the error happens ?

As you mentioned trying other libraries that had the same issue it might be related to the way you use them rather than de libraries themselves, but that's just a uneducated guess.

**Comment by YasinFatullayev** [comment]
I ran the bare minimum example and still got the error. Here are the steps that I followed and got the same error:
`1.  npx create-react-app my-app --template typescript`
 `2.  npm install react-ts-datatable`
 `3.  Add following code into source and run`
 
```javascript 

import { useTable } from 'react-ts-datatable'

const columns = [
    { id: 'firstName', displayText: 'First Name' },
    { id: 'lastName', displayText: 'Last Name' },
    { id: 'startDate', displayText: 'Start Date', sortMethod: 'sortDateISO' },
    { id: 'department', displayText: 'Department' },
    { id: 'dateOfBirth', displayText: 'Date of Birth', sortMethod: 'sortDateISO' },
    { id: 'street', displayText: 'Street' },
    { id: 'city', displayText: 'City'},
    { id: 'state', displayText: 'State' },
    { id: 'zipCode', displayText: 'Zip Code' },
  ]

  const data = [
    {
      key: '0224353f-726b-497f-9e46-97dfd516d673',
      firstName: 'Bernie',
      lastName: 'Swindin',
      department: 'Services',
      dateOfBirth: '03/10/1988',
      startDate: '08/18/2018',
      street: '6 Schiller Drive',
      city: 'Memphis',
      state: 'TN',
      zipCode: '38143',
    },
    {
      key: 'e092e395-2637-4bbc-b7bd-a8668f53b288',
      firstName: 'Jo',
      lastName: 'Barnsley',
      department: 'Legal',
      dateOfBirth: '11/23/1982',
      startDate: '05/09/2020',
      street: '7 Warner Way',
      city: 'Fort Worth',
      state: 'TX',
      zipCode: '76147',
    },
  ]

const Datatable=()=>{

    const {
        headers,
        rows,
        pagination,
        summary,
        isFiltered,
        handleSorting,
        handlePageSizing,
        handleFiltering,
        handlePageChange,
      } = useTable({ columns, data });

      return(
        <>{headers}</>
      )

}

export default Datatable; 
```
Error is happening in the `useTable({ columns, data });` hook.  and throws the `Invalid hook call` error [#ref](https://github.com/Allandrow/React-TS-dataTable/issues/1#issue-1405155776)
